select * from customer

--total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Customers that used a discount and still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' AND purchase_amount >= (select avg(purchase_amount) from customer)

--Top 5 products with highest average review rating
--select * from (select item_purchased, 
  --             avg(review_rating) as avg_rating, 
    --           dense_rank() over(order by avg(review_rating) desc) as rank
		--	   from customer 
		--	   group by item_purchased)
--where rank<=5

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Comparing average purchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type IN ('Express', 'Standard')
group by shipping_type

--Comparing average spend and total revenue between subscribers and non subscribers
select subscription_status, count(customer_id) as total_customers, 
       round(avg(purchase_amount),2) as average_spend, 
	   sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by average_spend, total_revenue  desc

--Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
        round(100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 5

--Segment customers into New, Returning, Loyal based on their total
-- number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
 WHEN previous_purchases = 1 then 'New'
 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
 ELSE 'Loyal'
END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number_of_Customers"
from customer_type
group by customer_segment

--Top 3 most purchased products within each category
select * from (select item_purchased, count(*) as item_count, category, 
       dense_rank() over(partition by category order by count(*) desc) as rank
from customer
group by category,item_purchased)
where rank<=3

--Are customers who are repeat buyers (>5 purchases) likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases>5 
group by subscription_status

--Revenue contribution of each group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc




 